name: Build and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: macos-14  # 👈 Fix: Use macOS-14 instead of macos-latest

    steps:
      - name: Set up job
        run: echo "Starting workflow"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Ensure .NET 9 SDK

      - name: Restore NuGet packages
        run: dotnet restore MobileApp/Engager_Mobile/Engager_Mobile.sln

      - name: Build project
        run: dotnet build MobileApp/Engager_Mobile/Engager_Mobile.sln --no-restore --configuration Release

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: MobileApp/Engager_Mobile
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
