name: SonarCloud Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      # Step 1: Set up Java if needed
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # Step 2: Install .NET (since you're using Xamarin)
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'  # Adjust if needed

      # Step 3: Restore and build the Xamarin project
      - name: Restore NuGet packages
        run: dotnet restore EngagerMobile.Mariteam/EngagerMobile.Mariteam.sln

      - name: Build project
        run: dotnet build EngagerMobile.Mariteam/EngagerMobile.Mariteam.sln --configuration Release

      # Step 4: Run SonarCloud scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

